# config.yaml

data:
  tickers:
    - "EURUSD=X"
    - "CNY=X"
    - "JPY=X"
    - "EURGBP=X"
  start_date: "2010-01-01"
  interval: "1d"
  features: ["Open", "High", "Low", "Close", "Volume"]
  time_step: 60
  test_size: 0.2
  validation_size: 0.1

model:
  input_size: 8  # Nombre d'entrées du modèle (8 features)
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  bidirectional: True

training:
  batch_size: 128
  epochs: 100
  learning_rate: 0.001
  patience: 10  # Patience pour l'arrêt anticipé

logging:
  level: "INFO"
  log_file: "training.log"

output:
  model_dir: "models/"
  plots_dir: "plots/"
